version: '3'

services:
  lecf:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: lecf
    restart: unless-stopped
    volumes:
      - ../certificates:/etc/letsencrypt
      - ../.env:/app/.env:ro
      - ../config.yaml:/app/config.yaml:ro
    environment:
      - TZ=UTC
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 